import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-24 lg:px-8">
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-10"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to home
      </Link>

      <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-muted-foreground">Last updated: February 2026</p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3">
        <p>
          OrgSync (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and protect information when you use our platform.
        </p>

        <h2>1. What We Collect</h2>
        <p>
          We collect information you provide directly (name, email, billing details), information generated by your use of the platform (sync configurations, execution logs, support tickets), and standard technical data (IP address, browser type, session data).
        </p>
        <p>
          <strong className="text-foreground">We do not store your Salesforce record data.</strong> OrgSync processes records in-memory during a sync and does not persist the values of Salesforce records. We store only metadata: record IDs, sync configurations, execution logs, and error messages.
        </p>

        <h2>2. Salesforce Access Tokens</h2>
        <p>
          To connect your Salesforce orgs, we store OAuth access tokens and refresh tokens encrypted at rest using AES-256-GCM encryption. These tokens are used solely to perform sync operations you have configured. We never share these tokens with third parties.
        </p>

        <h2>3. How We Use Your Information</h2>
        <p>We use your information to:</p>
        <ul className="list-disc pl-5 space-y-1.5 mt-2">
          <li>Provide, operate, and improve the OrgSync service</li>
          <li>Execute sync configurations on your behalf</li>
          <li>Send transactional emails (sync errors, account alerts)</li>
          <li>Respond to support requests</li>
          <li>Comply with legal obligations</li>
        </ul>

        <h2>4. Data Isolation</h2>
        <p>
          Each customer&apos;s data is isolated using Row Level Security (RLS) on our database. No customer can access another customer&apos;s sync configurations, logs, or connected org credentials.
        </p>

        <h2>5. Third-Party Services</h2>
        <p>We use the following third-party services:</p>
        <ul className="list-disc pl-5 space-y-1.5 mt-2">
          <li><strong className="text-foreground">Supabase</strong> — Database and authentication</li>
          <li><strong className="text-foreground">Stripe</strong> — Payment processing (we do not store card data)</li>
          <li><strong className="text-foreground">Anthropic Claude</strong> — AI-powered features (error explanation, mapping analysis). Only anonymized sync metadata is sent; no Salesforce record values are shared.</li>
          <li><strong className="text-foreground">Vercel / Railway</strong> — Hosting infrastructure</li>
        </ul>

        <h2>6. Data Retention</h2>
        <p>
          Sync logs are retained for 90 days. Sync configurations and connected org tokens are retained until you delete them. Account data is retained for 30 days after account deletion to allow recovery, then permanently deleted.
        </p>

        <h2>7. Your Rights</h2>
        <p>You may request to access, correct, or delete your data at any time by contacting us at <Link href="/about#contact" className="text-primary hover:underline">our contact page</Link>. We will respond within 30 days.</p>

        <h2>8. Security</h2>
        <p>
          We use industry-standard security practices including AES-256-GCM encryption for sensitive credentials, TLS for all data in transit, and regular security reviews. No method of transmission over the internet is 100% secure, but we take commercially reasonable steps to protect your data.
        </p>

        <h2>9. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy periodically. We will notify you of significant changes by email or by posting a notice in the platform. Your continued use of OrgSync after changes constitutes acceptance of the updated policy.
        </p>

        <h2>10. Contact</h2>
        <p>
          For privacy-related questions, contact us via <Link href="/about#contact" className="text-primary hover:underline">our contact page</Link>.
        </p>
      </div>
    </div>
  );
}
